import type { Metadata } from 'next'
import './globals.css'
import { cookies } from 'next/headers'
import { AppSidebar } from '@/components/app-sidebar'
import { ThemeProvider } from '@/components/theme-proviter'
import { Separator } from '@/components/ui/separator'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get('sidebar_state')?.value === 'true'

  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className="transition-all duration-300">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />
            <div className="py-4 px-1 flex-1">
              <div className="flex h-4 gap-2 space-x-1 items-center">
                <SidebarTrigger />
                <Separator orientation="vertical" />
                <p className="text-muted-foreground text-sm">App Layout</p>
              </div>
              <div className="p-2">{children}</div>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
